WebApp/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class Teacher
    {
        public int ID { get; set; }
        [Display(Name = "教師姓名")]
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public ICollection<WebApp.Models.CourseAssignment> CourseAssignment { get; set; }
    }
}

WebApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly WebAppContext _context;

        public TeachersController(WebAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public ActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Login([Bind("ID,Name,Account,Password")] String Password, String Account)
        {
            var member = _context.Teacher
                .Where(m => m.Account == Account && m.Password == Password)
                .FirstOrDefault();

            //驗證密碼
            if (member == null)
            {
                ViewBag.message = "帳密錯誤，登入失敗";
                return View();
            }
            HttpContext.Session.SetString("Welcome", "教師 " + member.Name);
            HttpContext.Session.SetInt32("member", member.ID);
            HttpContext.Session.SetString("Name", member.Name);
            HttpContext.Session.SetString("Teacher", "teacher");
            return RedirectToAction("index", "Teaches");
        }
        public async Task<IActionResult> PDetails()
        {
            var Member = HttpContext.Session.GetInt32("member");
            var Teacher = HttpContext.Session.GetString("Teacher");
            if (Teacher == null)
            {
                return NotFound();
            }
            if (Member == null)
            {
                return NotFound();
            }
            
            var teacher = await _context.Teacher
           .Include(s => s.CourseAssignment)
               .ThenInclude(e => e.Teach)
           .AsNoTracking()
           .FirstOrDefaultAsync(m => m.ID == Member);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }
        public async Task<IActionResult> Index()
        {
            var Teacher = HttpContext.Session.GetString("Teacher");
            if (Teacher == null)
            {
                return NotFound();
            }
            return View(await _context.Teacher.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var Teacher = HttpContext.Session.GetString("Teacher");
            if (Teacher == null)
            {
                return NotFound();
            }
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }
        public async Task<IActionResult> List(int? id)
        {
            var Teacher = HttpContext.Session.GetString("Teacher");
            if (Teacher == null)
            {
                return NotFound();
            }
            if (id == null)
            {
                return NotFound();
            }

            var teacher =  await _context.Teach
                            .Include(s => s.Enrollment)
               .ThenInclude(e => e.Students)
                            .AsNoTracking()
                            .FirstOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }
        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Account,Password")] Teacher teacher)
        {
            
            if (ModelState.IsValid)
            {

                var stu = _context.Teacher
                         .Where(m => m.Account == teacher.Account)
                         .FirstOrDefault();
                if (stu == null)
                {
                    _context.Add(teacher);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Login));
                }
                ViewBag.msg = "此帳號已有人使用註冊失敗";
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit()
        {
            var Teacher = HttpContext.Session.GetString("Teacher");
            var Member = HttpContext.Session.GetInt32("member");
            if (Teacher == null)
            {
                return NotFound();
            }
            if (Member == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(Member);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ID,Name,Account,Password")] Teacher teacher)
        {
            var Member = HttpContext.Session.GetInt32("member");
            teacher.ID = (int)Member;
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                ViewBag.message = "修改成功";
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var Teacher = HttpContext.Session.GetString("Teacher");
            if (Teacher == null)
            {
                return NotFound();
            }
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.ID == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.ID == id);
        }
    }
}

WebApp/Views/Teachers/Create.cshtml
@model WebApp.Models.Teacher

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout Login";
}

<h2>教師註冊</h2>
<a asp-controller="Teachers" asp-action="Create" class="btn btn-primary"> 教師 </a>
<a asp-controller="students" asp-action="Create" class="btn btn-primary "> 學生</a>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">姓名</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account" class="control-label">帳號(教師證)</label>
                <input asp-for="Account" class="form-control" />
                <span asp-validation-for="Account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">密碼</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div>
                <label>

                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="註冊" class="btn btn-primary" />
                <label style="color:red;">@ViewBag.message</label>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Teachers/Delete.cshtml
@model WebApp.Models.Teacher

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout Teacher";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Teachers/Details.cshtml
@model WebApp.Models.Teacher

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout Teacher";
}

<h1>Details</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Views/Teachers/Edit.cshtml
@model WebApp.Models.Teacher

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout Teacher";
}
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Edit";
    var Member = HttpContextAccessor.HttpContext.Session.GetString("Member");
}

<h2>更改個人資料</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Member" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Account" class="control-label">帳號</label>
                <input asp-for="Account" class="form-control" readonly />
                <span asp-validation-for="Account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label">密碼</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div>
                <label>

                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="保存" class="btn btn-primary" />
                <label style="color:blue;">@ViewBag.Message</label>
            </div>

        </form>
    </div>
</div>
<div>
    <label>

    </label>
</div>
<div>

    <a asp-controller="Teaches" asp-action="index">回到課程清單</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Teachers/Index.cshtml
@model IEnumerable<WebApp.Models.Teacher>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout Teacher";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Account)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Account)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApp/Views/Teachers/List.cshtml
@model WebApp.Models.Teach

@{
    ViewData["Title"] = "學生名單";
    Layout = "_Layout Teacher";
}

<h1>選課學生名單</h1>

<div>
    <hr />
    <dl class="row">
        
            <dt class="col-sm-2">
                @Html.DisplayNameFor(m =>m.Course)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(m =>m.Course)
            </dd>
        
        <dt class="col-sm-2">
            學生資料
        </dt>
        <dd class="col-sm-10">
            <table class="table">


                <tr>
                    <td>
                        學號
                    </td>
                    <td>
                        學生姓名
                    </td>

                </tr>

                @foreach (var item in Model.Enrollment)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Students.Account)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Students.Name)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>

WebApp/Views/Teachers/Login.cshtml
@model WebApp.Models.Teacher

@{
    Layout = "_Layout Login";
    ViewBag.Title = "教師登入";
}
<h2>教師登入</h2>

<a asp-controller="Teachers" asp-action="login" class="btn btn-primary"> 教師 </a>
<a asp-controller="students" asp-action="login" class="btn btn-primary "> 學生</a>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div class="form-group">
                <label asp-for="Account" class="control-label">帳號</label>
                <input asp-for="Account" class="form-control" />
                <span asp-validation-for="Account" class="text-danger"></span>
                <small id="emailHelp" class="form-text text-muted  col-md-10">請輸入教師證號碼</small>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label">密碼</label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
                <small id="emailHelp" class="form-text text-muted col-md-10">請輸入數字</small>

            </div>
            <div class="form-group">
                <input type="submit" value="登入" class="btn btn-primary" />
                @ViewBag.message
            </div>
        </form>
    </div>
</div>

WebApp/Views/Teachers/PDetails.cshtml
@model WebApp.Models.Teacher

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout Teacher";
}

<h1>課程名單</h1>

<div> 
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            課程資料
        </dt>
        <dd class="col-sm-10">
            <table class="table">


                
                    <tr>
                        <td>
                            課程
                        </td>
                        <td>
                            教師姓名
                        </td>
                        <td>
                            時段
                        </td>

                        <td>
                            星期
                        </td>
                        <td>
                            教室
                        </td>
                        <td>
                            類別
                        </td>
                        <td>
                            學分
                        </td>
                        
                    </tr>
                
                @foreach (var item in Model.CourseAssignment)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.Course)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.ClassDate)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.Rating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.Classroom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Teach.credit)
                        </td>
                        <td>
                            <a asp-controller="Teachers" asp-action="List" asp-route-id="@item.TeachID">學生名單</a> |
                            <a asp-controller="teaches" asp-action="Edit" asp-route-id="@item.TeachID">編輯</a> |
                            <a asp-controller="teaches" asp-action="Delete" asp-route-id="@item.TeachID">刪除</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>